name: retro_star_env
channels:
  - rdkit
  - conda-forge
  - pytorch
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - torchvision
  - cpuonly
  - pytorch
  - pandas
  - rdkit
  - tqdm
  - networkx
  - setproctitle
  - graphviz
  - python-graphviz
prefix: $CONDA_PREFIX

